server:
  port: 7090
  
spring:
  datasource:
#    url: jdbc:h2:mem:localdb
    url: jdbc:h2:file:./h2/localdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
  flyway:
    user: sa
    password: password
    url: jdbc:h2:file:./h2/localdb
    locations:
    - classpath:db/migration  
    baseline-on-migrate: true